services:
  db:
    image: postgres:15
    container_name: wallet-db
    environment:
      POSTGRES_USER: ramoo19
      POSTGRES_PASSWORD: 12341234
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: wallet-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: wallet-app
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL:-jdbc:postgresql://db:5432/wallet_db}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-ramoo19}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-12341234}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ramilastanli19@gmail.com
      SPRING_MAIL_PASSWORD: ${SMTP_PASS}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

      SPRING_DATA_REDIS_HOST: ${REDIS_HOST:-redis}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT:-6379}

      APP_JWT_SECRET: ${JWT_SECRET:-ZmFzdC13YWxsZXQtYXBwLXNlY3JldC1rZXktZm9yLTIwMjY=}
      APP_JWT_EXPIRATION: 900000
      APP_JWT_REFRESH_EXPIRATION: 604800000

  nginx:
    image: nginx:latest
    container_name: wallet-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  postgres_data: